[;Comments]
;All paths can be absolute or relative to the DLL location = 
;This is the configuration file for HKDLLInitializer = 

[Application]
Arguments = 
FallbackArguments = 
FallbackPath = 
Path = Hollow Knight.exe

[Logging]
EnableConsoleLogging = true
LogFile = HKDLLInitializer.log

[Unix]
EnableUnixSupport = true
UnixPaths = /usr/bin:/usr/local/bin

